In [ ]:
import numpy as np

In [11]:
A = np.array([[2, 4, 5], [5, 6, 7]])
B = np.ones_like(A)
C = np.zeros_like(A)
print(A)
print(B)
print(C)

[[2 4 5]
 [5 6 7]]
[[1 1 1]
 [1 1 1]]
[[0 0 0]
 [0 0 0]]


In [14]:
print(np.ones(2))

[1. 1.]


In [16]:
print(np.ones((1,2)))

[[1. 1.]]


In [17]:
print(np.ones((2,1)))

[[1.]
 [1.]]


In [20]:
help(np.fromfunction)

Help on function fromfunction in module numpy:

fromfunction(function, shape, *, dtype=<class 'float'>, like=None, **kwargs)
    Construct an array by executing a function over each coordinate.
    
    The resulting array therefore has a value ``fn(x, y, z)`` at
    coordinate ``(x, y, z)``.
    
    Parameters
    ----------
    function : callable
        The function is called with N parameters, where N is the rank of
        `shape`.  Each parameter represents the coordinates of the array
        varying along a specific axis.  For example, if `shape`
        were ``(2, 2)``, then the parameters would be
        ``array([[0, 0], [1, 1]])`` and ``array([[0, 1], [0, 1]])``
    shape : (N,) tuple of ints
        Shape of the output array, which also determines the shape of
        the coordinate arrays passed to `function`.
    dtype : data-type, optional
        Data-type of the coordinate arrays passed to `function`.
        By default, `dtype` is float.
    like : array_like, opti